"""initial_schema

Revision ID: 0d16b8c0fc52
Revises: 
Create Date: 2026-09-15 21:07:18.993722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision: str = '0d16b8c0fc52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('callsign', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icao_code')
    )
    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airlines_iata_code'), ['iata_code'], unique=True)

    op.create_table('airports',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icao_code')
    )
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airports_iata_code'), ['iata_code'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('user_id', models.UUIDType(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', models.UUIDType(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_email'), ['user_email'], unique=False)

    op.create_table('data_sources',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_source_name'), ['source_name'], unique=True)

    op.create_table('dgca_benchmarks',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('reference_period', sa.Date(), nullable=False),
    sa.Column('route_code', sa.String(length=10), nullable=True),
    sa.Column('avg_fare_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('median_fare_inr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_passengers', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('publication_url', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dgca_benchmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dgca_benchmarks_reference_period'), ['reference_period'], unique=True)
        batch_op.create_index(batch_op.f('ix_dgca_benchmarks_route_code'), ['route_code'], unique=False)

    op.create_table('methodology_versions',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('version_code', sa.String(length=20), nullable=False),
    sa.Column('formula_name', sa.String(length=50), nullable=False),
    sa.Column('base_period_start', sa.Date(), nullable=False),
    sa.Column('base_period_end', sa.Date(), nullable=False),
    sa.Column('base_index_value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('aggregation_rules', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('methodology_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_methodology_versions_version_code'), ['version_code'], unique=True)

    op.create_table('users',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('index_baskets',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('basket_name', sa.String(length=100), nullable=False),
    sa.Column('methodology_version_id', models.UUIDType(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('basket_name')
    )
    op.create_table('routes',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('origin_airport_id', models.UUIDType(), nullable=False),
    sa.Column('destination_airport_id', models.UUIDType(), nullable=False),
    sa.Column('route_code', sa.String(length=10), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('dgca_category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['origin_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_route_code'), ['route_code'], unique=True)

    op.create_table('aggregate_indices',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('methodology_version_id', models.UUIDType(), nullable=False),
    sa.Column('index_basket_id', models.UUIDType(), nullable=False),
    sa.Column('index_date', sa.Date(), nullable=False),
    sa.Column('national_index', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('daily_change_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('weekly_change_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('monthly_change_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('total_observations', sa.Integer(), nullable=False),
    sa.Column('total_routes_active', sa.Integer(), nullable=False),
    sa.Column('total_routes_covered', sa.Integer(), nullable=False),
    sa.Column('coverage_ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['index_basket_id'], ['index_baskets.id'], ),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('methodology_version_id', 'index_date', 'revision_number', name='uq_agg_index_date')
    )
    with op.batch_alter_table('aggregate_indices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aggregate_indices_index_date'), ['index_date'], unique=False)

    op.create_table('backtest_runs',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('methodology_version_id', models.UUIDType(), nullable=False),
    sa.Column('index_basket_id', models.UUIDType(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reference_benchmark_name', sa.String(length=100), nullable=False),
    sa.Column('mae', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rmse', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('mape', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('correlation', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['index_basket_id'], ['index_baskets.id'], ),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_jobs',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('source_id', models.UUIDType(), nullable=False),
    sa.Column('route_id', models.UUIDType(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('advance_purchase_days', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_jobs_status'), ['status'], unique=False)

    op.create_table('index_basket_routes',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('index_basket_id', models.UUIDType(), nullable=False),
    sa.Column('route_id', models.UUIDType(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['index_basket_id'], ['index_baskets.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('index_basket_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_index_basket_routes_index_basket_id'), ['index_basket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_index_basket_routes_route_id'), ['route_id'], unique=False)

    op.create_table('route_indices',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('methodology_version_id', models.UUIDType(), nullable=False),
    sa.Column('route_id', models.UUIDType(), nullable=False),
    sa.Column('index_date', sa.Date(), nullable=False),
    sa.Column('current_index', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('base_median_fare', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_median_fare', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_mean_fare', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('valid_observation_count', sa.Integer(), nullable=False),
    sa.Column('coverage_ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('daily_change_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('weekly_change_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('monthly_change_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('booking_window_data', sa.JSON(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('methodology_version_id', 'route_id', 'index_date', 'revision_number', name='uq_route_index_date')
    )
    with op.batch_alter_table('route_indices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_indices_index_date'), ['index_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_indices_route_id'), ['route_id'], unique=False)

    op.create_table('collection_runs',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('job_id', models.UUIDType(), nullable=True),
    sa.Column('source_id', models.UUIDType(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_observed', sa.Integer(), nullable=False),
    sa.Column('records_valid', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_s3_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['collection_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_runs_status'), ['status'], unique=False)

    op.create_table('flight_observations',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('collection_run_id', models.UUIDType(), nullable=False),
    sa.Column('airline_id', models.UUIDType(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('origin_airport_id', models.UUIDType(), nullable=False),
    sa.Column('destination_airport_id', models.UUIDType(), nullable=False),
    sa.Column('departure_datetime', sa.DateTime(), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=False),
    sa.Column('is_non_stop', sa.Boolean(), nullable=False),
    sa.Column('stops_count', sa.Integer(), nullable=False),
    sa.Column('aircraft_type', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], ),
    sa.ForeignKeyConstraint(['destination_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['origin_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flight_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flight_observations_airline_id'), ['airline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_observations_collection_run_id'), ['collection_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_observations_departure_datetime'), ['departure_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_observations_destination_airport_id'), ['destination_airport_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_observations_origin_airport_id'), ['origin_airport_id'], unique=False)

    op.create_table('fare_observations',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('flight_observation_id', models.UUIDType(), nullable=False),
    sa.Column('source_id', models.UUIDType(), nullable=False),
    sa.Column('cabin_class', sa.String(length=20), nullable=False),
    sa.Column('fare_class', sa.String(length=10), nullable=False),
    sa.Column('advance_purchase_days', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('user_development_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('convenience_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fuel_surcharge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_fees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_fare', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('seats_remaining', sa.Integer(), nullable=True),
    sa.Column('source_url_or_ref', sa.Text(), nullable=True),
    sa.Column('raw_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_s3_uri', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flight_observation_id'], ['flight_observations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fare_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fare_observations_advance_purchase_days'), ['advance_purchase_days'], unique=False)
        batch_op.create_index(batch_op.f('ix_fare_observations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fare_observations_flight_observation_id'), ['flight_observation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fare_observations_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fare_observations_total_fare'), ['total_fare'], unique=False)
        batch_op.create_index(batch_op.f('ix_fare_observations_validation_status'), ['validation_status'], unique=False)

    op.create_table('anomaly_events',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('fare_observation_id', models.UUIDType(), nullable=False),
    sa.Column('route_id', models.UUIDType(), nullable=False),
    sa.Column('advance_purchase_days', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_range_lower', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_range_upper', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fare_observation_id'], ['fare_observations.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_events_fare_observation_id'), ['fare_observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_events_route_id'), ['route_id'], unique=False)

    op.create_table('fare_components',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('fare_observation_id', models.UUIDType(), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fare_observation_id'], ['fare_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fare_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fare_components_fare_observation_id'), ['fare_observation_id'], unique=False)

    op.create_table('quality_results',
    sa.Column('id', models.UUIDType(), nullable=False),
    sa.Column('fare_observation_id', models.UUIDType(), nullable=False),
    sa.Column('check_name', sa.String(length=100), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fare_observation_id'], ['fare_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_results_fare_observation_id'), ['fare_observation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_results_fare_observation_id'))

    op.drop_table('quality_results')
    with op.batch_alter_table('fare_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fare_components_fare_observation_id'))

    op.drop_table('fare_components')
    with op.batch_alter_table('anomaly_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_events_route_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_events_fare_observation_id'))

    op.drop_table('anomaly_events')
    with op.batch_alter_table('fare_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fare_observations_validation_status'))
        batch_op.drop_index(batch_op.f('ix_fare_observations_total_fare'))
        batch_op.drop_index(batch_op.f('ix_fare_observations_source_id'))
        batch_op.drop_index(batch_op.f('ix_fare_observations_flight_observation_id'))
        batch_op.drop_index(batch_op.f('ix_fare_observations_created_at'))
        batch_op.drop_index(batch_op.f('ix_fare_observations_advance_purchase_days'))

    op.drop_table('fare_observations')
    with op.batch_alter_table('flight_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flight_observations_origin_airport_id'))
        batch_op.drop_index(batch_op.f('ix_flight_observations_destination_airport_id'))
        batch_op.drop_index(batch_op.f('ix_flight_observations_departure_datetime'))
        batch_op.drop_index(batch_op.f('ix_flight_observations_collection_run_id'))
        batch_op.drop_index(batch_op.f('ix_flight_observations_airline_id'))

    op.drop_table('flight_observations')
    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_runs_status'))

    op.drop_table('collection_runs')
    with op.batch_alter_table('route_indices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_indices_route_id'))
        batch_op.drop_index(batch_op.f('ix_route_indices_index_date'))

    op.drop_table('route_indices')
    with op.batch_alter_table('index_basket_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_index_basket_routes_route_id'))
        batch_op.drop_index(batch_op.f('ix_index_basket_routes_index_basket_id'))

    op.drop_table('index_basket_routes')
    with op.batch_alter_table('collection_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_jobs_status'))

    op.drop_table('collection_jobs')
    op.drop_table('backtest_runs')
    with op.batch_alter_table('aggregate_indices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aggregate_indices_index_date'))

    op.drop_table('aggregate_indices')
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_route_code'))

    op.drop_table('routes')
    op.drop_table('index_baskets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('methodology_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_methodology_versions_version_code'))

    op.drop_table('methodology_versions')
    with op.batch_alter_table('dgca_benchmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dgca_benchmarks_route_code'))
        batch_op.drop_index(batch_op.f('ix_dgca_benchmarks_reference_period'))

    op.drop_table('dgca_benchmarks')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_source_name'))

    op.drop_table('data_sources')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_email'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airports_iata_code'))

    op.drop_table('airports')
    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airlines_iata_code'))

    op.drop_table('airlines')
    # ### end Alembic commands ###
